/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OVhEl32zxxm
 */
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import Image from "next/image"
import LinkTransition from "./LinkTransition"
import { MyCard } from "./MyCard"
export function ResumeHome() {
  return (
    <div className="flex flex-col items-center p-6 space-y-6">
      <section className="rounded-lg  bg-[rgba(255,255,255,0.2)] text-card-foreground p-5 flex items-center space-x-4">
        <Image
          alt="Developer Avatar"
          className="w-24 h-24 rounded-full"
          height="100"
          src="/images/avatar.jpg"
          style={{
            aspectRatio: "100/100",
            objectFit: "cover",
          }}
          width="100"
        />
        <div className="max-w-80">
          <h1 className="text-2xl font-bold">Puria Kordrostami</h1>
          <p className=" text-md leading-tight text-gray-600 ">
            12 years of experience in the field of IT. with a passion to create things and solve problems. My goal is to become able to manage an IT business.
          </p>
        </div>
      </section>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <LinkTransition href="/front-end">
          <MyCard>
            <Card className="relative group-hover:bgapply rounded-md border shadow-lg overflow-hidden transition-all duration-300 ease-in-out">
              <CardHeader className="p-4 bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 group-hover:bg-gradient-to-r group-hover:from-green-400 group-hover:via-blue-500 group-hover:to-purple-500 transition-all duration-500 ease-in-out text-transparent bg-clip-text">
                <Badge className="text-sm font-semibold" variant="secondary">
                  Frontend
                </Badge>
                <h2 className="text-2xl font-bold mt-2">Frontend Developer</h2>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-sm font-medium text-gray-500">
                  Specializes in the development of a user interface for websites or web applications. Skilled in
                  implementing visual and interactive elements.
                </p>
                <ul className="list-disc list-inside mt-2">
                  <li>JavaScript Frameworks</li>
                  <li>User Experience Design</li>
                  <li>Performance Optimization</li>
                </ul>
                <Button className="mt-4" variant="link">
                  View Full Resume
                </Button>
              </CardContent>
            </Card>
          </MyCard>
        </LinkTransition>
        <LinkTransition href="/back-end">
          <MyCard>
            <Card className="relative bg-card group-hover:bgapply rounded-md border shadow-lg overflow-hidden transition-all duration-300 ease-in-out">
              <CardHeader className="p-4 bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 group-hover:bg-gradient-to-r group-hover:from-green-400 group-hover:via-blue-500 group-hover:to-purple-500 transition-all duration-500 ease-in-out text-transparent bg-clip-text">
                <Badge className="text-sm font-semibold" variant="secondary">
                  Backend
                </Badge>
                <h2 className="text-2xl font-bold mt-2">Backend Developer</h2>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-sm font-medium text-gray-500">
                  Focused on server-side application logic, databases, server configuration, and data interchange between
                  server and client.
                </p>
                <ul className="list-disc list-inside mt-2">
                  <li>API Development</li>
                  <li>Database Management</li>
                  <li>Server Configuration</li>
                </ul>
                <Button className="mt-4" variant="link">
                  View Full Resume
                </Button>
              </CardContent>
            </Card>
          </MyCard>
        </LinkTransition>
        <LinkTransition href="/dev-ops">
          <MyCard>
            <Card className="relative group-hover:bgapply rounded-md border shadow-lg overflow-hidden transition-all duration-300 ease-in-out">
              <CardHeader className="p-4 bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 group-hover:bg-gradient-to-r group-hover:from-green-400 group-hover:via-blue-500 group-hover:to-purple-500 transition-all duration-300 ease-in-out text-transparent bg-clip-text">
                <Badge className="text-sm font-semibold" variant="secondary">
                  DevOps
                </Badge>
                <h2 className="text-2xl font-bold mt-2">DevOps Engineer</h2>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-sm font-medium text-gray-500">
                  Specializing in deployment automation, infrastructure optimization, and maintaining organizational
                  infrastructure.
                </p>
                <ul className="list-disc list-inside mt-2">
                  <li>Cloud Infrastructure</li>
                  <li>CI/CD Pipelines</li>
                  <li>Infrastructure as Code (IAC)</li>
                </ul>
                <Button className="mt-4" variant="link">
                  View Full Resume
                </Button>
              </CardContent>
            </Card>
          </MyCard>
        </LinkTransition>
      </div>
    </div>
  )
}
